Repository tcbutler320/Jekyll-Theme-Dumbarton, pull requests merged in 2020-11, with the labels that each got.

#27 Update for v1.0
  README.md
  _bibliography/papers.bib
  _bibliography/presentations.bib
  _config.yml
  _data/teaching.yml
  _includes/footer.html
  _includes/head-blog.html
  _includes/head.html
  _includes/nav.html
  _includes/social.html
  _layouts/home.html
  _layouts/post-2.html
  _layouts/post.html
  _posts/2020-10-26-Lorem-Ipsum.md
  _posts/2020-10-26-Lorem-Ipsum2.md
  _posts/2020-10-27-Jekyll-Is-Better-Then-Gatsby.md
  _posts/2020-10-28-Dumbarton-Style-Guide.md
  _posts/2020-10-29-welcome-to-jekyll.md
  assets/docx/vitae.docx
  assets/img/1x/example.png
  assets/img/example.jpeg
  assets/img/projects/project1.jpeg
  assets/img/projects/project2.jpeg
  assets/img/projects/project3.jpeg
  assets/img/projects/project5.jpeg
  assets/img/publications.png
  assets/pdf/example.pdf
  pages/blog.html
  pages/contact.html
  pages/docs.html
  pages/publications.html
Labels: documentation, enhancement

#33 Add Project Technologies Badge
  1x/dumbarton250x200.png
  CHANGELOG.md
  _config.yml
  _data/projects.yml
  _layouts/home.html
  netlify.toml
  package.json
Labels: enhancement

#37 Remove borders, Update Readme, Improve Footer
  Dumbarton.gemspec
  README.md
  _config.yml
  _data/education.yml
  _includes/footer.html
  _includes/social-footer.html
  _layouts/docs.html
  _layouts/home.html
  _layouts/page.html
  assets/img/avatar/cropped.png
  index.md
  screenshot.png
Labels: documentation, enhancement

#38 Docs: Update readme
  README.md
Labels: documentation

#42 Docs Update
  CHANGELOG.md
  README.md
Labels: documentation
